<?php
/**
 * ZC Charts Admin Settings Page
 * Main configuration page for the plugin
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

// Check user capabilities
if (!current_user_can('manage_options')) {
    return;
}

// Handle form submissions
if (isset($_POST['submit']) && isset($_POST['zc_charts_settings_nonce'])) {
    // Verify nonce
    if (!wp_verify_nonce($_POST['zc_charts_settings_nonce'], 'zc_charts_save_settings')) {
        wp_die(__('Security check failed', 'zc-charts'));
    }
    
    // Save settings
    $api_key = sanitize_text_field($_POST['zc_charts_api_key']);
    $default_library = sanitize_key($_POST['zc_charts_default_library']);
    
    update_option('zc_charts_api_key', $api_key);
    update_option('zc_charts_default_library', $default_library);
    
    // Add success notice
    add_action('admin_notices', function() {
        ?>
        <div class="notice notice-success">
            <p><?php _e('Settings saved successfully.', 'zc-charts'); ?></p>
        </div>
        <?php
    });
}

// Handle test connection
$connection_test_result = null;
if (isset($_POST['test_connection']) && isset($_POST['zc_charts_settings_nonce'])) {
    // Verify nonce
    if (!wp_verify_nonce($_POST['zc_charts_settings_nonce'], 'zc_charts_save_settings')) {
        wp_die(__('Security check failed', 'zc-charts'));
    }
    
    // Test connection
    if (class_exists('ZC_Charts_API_Client')) {
        $api_client = new ZC_Charts_API_Client();
        $connection_test_result = $api_client->test_connection();
    }
}

// Get current settings
$current_api_key = get_option('zc_charts_api_key', '');
$current_default_library = get_option('zc_charts_default_library', 'chartjs');

// Get available API keys from DMT plugin
$dmt_api_keys = array();
if (class_exists('ZC_DMT_Security')) {
    $dmt_security = new ZC_DMT_Security();
    $dmt_api_keys = $dmt_security->get_all_keys();
}
?>

<div class="wrap zc-charts-settings-page">
    <h1><?php echo esc_html(get_admin_page_title()); ?></h1>
    
    <?php settings_errors(); ?>
    
    <form method="post" action="">
        <?php wp_nonce_field('zc_charts_save_settings', 'zc_charts_settings_nonce'); ?>
        
        <table class="form-table">
            <tr>
                <th scope="row"><?php _e('API Key', 'zc-charts'); ?></th>
                <td>
                    <select name="zc_charts_api_key" id="zc_charts_api_key">
                        <option value=""><?php _e('Select API Key', 'zc-charts'); ?></option>
                        <?php foreach ($dmt_api_keys as $key) : ?>
                            <option value="<?php echo esc_attr($key['key_hash']); ?>" <?php selected($current_api_key, $key['key_hash']); ?>>
                                <?php echo esc_html($key['key_name']); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <p class="description"><?php _e('Select the API key generated by the ZC DMT plugin.', 'zc-charts'); ?></p>
                    
                    <?php if (!empty($current_api_key)) : ?>
                        <div class="zc-charts-api-key-status <?php echo class_exists('ZC_Charts_Security') && ZC_Charts_Security::validate_api_key($current_api_key) ? 'valid' : 'invalid'; ?>">
                            <?php 
                            if (class_exists('ZC_Charts_Security')) {
                                $security = new ZC_Charts_Security();
                                if ($security->validate_api_key($current_api_key)) {
                                    _e('API key is valid and connected to ZC DMT.', 'zc-charts');
                                } else {
                                    _e('API key is invalid or cannot connect to ZC DMT.', 'zc-charts');
                                }
                            }
                            ?>
                        </div>
                    <?php endif; ?>
                </td>
            </tr>
            
            <tr>
                <th scope="row"><?php _e('Default Chart Library', 'zc-charts'); ?></th>
                <td>
                    <fieldset>
                        <label>
                            <input type="radio" name="zc_charts_default_library" value="chartjs" <?php checked($current_default_library, 'chartjs'); ?>>
                            <span><?php _e('Chart.js', 'zc-charts'); ?></span>
                        </label>
                        <br>
                        <label>
                            <input type="radio" name="zc_charts_default_library" value="highcharts" <?php checked($current_default_library, 'highcharts'); ?>>
                            <span><?php _e('Highcharts', 'zc-charts'); ?></span>
                        </label>
                    </fieldset>
                    <p class="description"><?php _e('Select the default chart library to use for rendering charts.', 'zc-charts'); ?></p>
                </td>
            </tr>
        </table>
        
        <?php submit_button(__('Save Changes', 'zc-charts')); ?>
        
        <p class="submit">
            <?php submit_button(__('Test Connection', 'zc-charts'), 'secondary', 'test_connection', false); ?>
        </p>
        
        <?php if ($connection_test_result !== null) : ?>
            <div class="zc-charts-test-connection-result <?php echo is_wp_error($connection_test_result) ? 'error' : 'success'; ?>">
                <?php 
                if (is_wp_error($connection_test_result)) {
                    echo esc_html($connection_test_result->get_error_message());
                } else {
                    _e('Connection to ZC DMT successful!', 'zc-charts');
                }
                ?>
            </div>
        <?php endif; ?>
    </form>
    
    <div class="zc-charts-help-section">
        <h2><?php _e('How to Use ZC Charts', 'zc-charts'); ?></h2>
        
        <p><?php _e('After configuring your API key, you can display charts on your site using shortcodes.', 'zc-charts'); ?></p>
        
        <div class="zc-charts-shortcode-example">
            <h3><?php _e('Dynamic Chart Shortcode', 'zc-charts'); ?></h3>
            <code>[zc_chart_dynamic id="indicator-slug" library="chartjs" timeframe="1y" height="400px"]</code>
            <p class="description"><?php _e('Displays an interactive chart with configurable timeframe and height.', 'zc-charts'); ?></p>
        </div>
        
        <div class="zc-charts-shortcode-example">
            <h3><?php _e('Static Chart Shortcode', 'zc-charts'); ?></h3>
            <code>[zc_chart_static id="indicator-slug" library="highcharts"]</code>
            <p class="description"><?php _e('Displays a static chart without interactive controls.', 'zc-charts'); ?></p>
        </div>
        
        <h3><?php _e('Parameters', 'zc-charts'); ?></h3>
        <ul>
            <li><strong>id</strong> (<?php _e('required', 'zc-charts'); ?>): <?php _e('The slug of the indicator to display (configured in ZC DMT).', 'zc-charts'); ?></li>
            <li><strong>library</strong> (<?php _e('optional', 'zc-charts'); ?>): <?php _e('Chart library to use (chartjs or highcharts). Defaults to the setting above.', 'zc-charts'); ?></li>
            <li><strong>timeframe</strong> (<?php _e('optional', 'zc-charts'); ?>): <?php _e('Time period to display (3m, 6m, 1y, 2y, 3y, 5y, 10y, 15y, 20y, 25y, all). Only for dynamic charts.', 'zc-charts'); ?></li>
            <li><strong>height</strong> (<?php _e('optional', 'zc-charts'); ?>): <?php _e('Height of the chart container. Only for dynamic charts.', 'zc-charts'); ?></li>
        </ul>
    </div>
</div>